package com.gorley.tweetapp.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;


@DynamoDBTable(tableName = "reply")
@Data
public class ReplyTweet {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    private String message;

    private String tweetId;

    private String userID;

    private String timeStamp;
}
