package com.gorley.tweetapp.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

@Builder
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@DynamoDBTable(tableName = "tweet")
@Data
public class Tweet {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    private String message;

    private String userID;

    private String timeStamp;
}
